### PR TITLE
force WS_X11 tag on FreeBSD

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description

@manisandro 

Follow-up https://github.com/qgis/QGIS/pull/45128#issuecomment-922444275

### CODE REVIEW

**Comment by manisandro** [comment]
Just for curiosity, what error do you get without setting WS_X11?

**Comment by lbartoletti** [comment]
the "classical" error: `sip-build: Q_PID is undefined` Every time, it's because of this missing tag, but I've never looked into why

**Comment by manisandro** [comment]
Thanks - I've updated the commit to add the platform tag for all supported platforms.

**Comment by lbartoletti** [comment]
Thanks sandro!

**Pull request closed without merging**
